apiVersion: 1

datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: webstore-traces
          name: trace_id

        - url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI

        - url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22tempo%22,%7B%22query%22:%22$${value}%22%7D%5D'
          name: trace_id
          urlDisplayLabel: View in Grafana UI (from Tempo)
